# Generated by Django 4.0.5 on 2022-06-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
